Цель работы: Целью работы является в том,что нужно поработать с анализом датасета.

In [ ]:
import pandas as pd
import numpy as np

Импортируем pandas and numpy.

In [ ]:
starwars = pd.read_csv("star_wars_character_dataset.csv")

starwars

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19.0,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,NaN,gold,yellow,112.0,none,masculine,Tatooine,Droid,"The Empire Strikes Back, Attack of the Clones,...",NaN,NaN
2,R2-D2,96.0,32.0,NaN,"white, blue",red,33.0,none,masculine,Naboo,Droid,"The Empire Strikes Back, Attack of the Clones,...",NaN,NaN
3,Darth Vader,202.0,136.0,none,white,yellow,41.9,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...",NaN,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,brown,19.0,female,feminine,Alderaan,Human,"The Empire Strikes Back, Revenge of the Sith, ...",Imperial Speeder Bike,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,feminine,NaN,Human,The Force Awakens,NaN,NaN
83,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,masculine,NaN,Human,The Force Awakens,NaN,T-70 X-wing fighter
84,BB8,NaN,NaN,none,none,black,NaN,none,masculine,NaN,Droid,The Force Awakens,NaN,NaN
85,Captain Phasma,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,The Force Awakens,NaN,NaN
86,Padmé Amidala,165.0,45.0,brown,light,brown,46.0,female,feminine,Naboo,Human,"Attack of the Clones, The Phantom Menace, Reve...",NaN,"H-type Nubian yacht, Naboo star skiff, Naboo f..."

Тут вывод всей информации из csv.

In [ ]:
print(starwars.shape)

(87, 14)

Далее через print вывели размерность масива.

In [ ]:
print(starwars.columns)

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'sex', 'gender', 'homeworld', 'species', 'films',
       'vehicles', 'starships'],
      dtype='object')

Вывод всех столбцов наименований,то есть: имя,рост,масса,цвет волос,цвет кожы, цвет глаз, год рождения, пол, гендер, родной мир, вид,фильмы,транспортное средство, звездолеты.

In [ ]:
starwars.nunique()

name          87
height        45
mass          38
hair_color    12
skin_color    31
eye_color     15
birth_year    36
sex            4
gender         2
homeworld     48
species       37
films         24
vehicles      10
starships     16
dtype: int64

Потом идет вывод уникальных значений

In [ ]:
starwars.sort_values(by='name')

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
25,Ackbar,180.0,83.0,none,brown mottle,orange,41.0,male,masculine,Mon Cala,Mon Calamari,"Return of the Jedi, The Force Awakens",NaN,NaN
51,Adi Gallia,184.0,50.0,none,dark,blue,NaN,female,feminine,Coruscant,Tholothian,"The Phantom Menace, Revenge of the Sith",NaN,NaN
10,Anakin Skywalker,188.0,84.0,blond,fair,blue,41.9,male,masculine,Tatooine,Human,"Attack of the Clones, The Phantom Menace, Reve...","Zephyr-G swoop bike, XJ-6 airspeeder","Trade Federation cruiser, Jedi Interceptor, Na..."
27,Arvel Crynyd,NaN,NaN,brown,fair,brown,NaN,male,masculine,NaN,Human,Return of the Jedi,NaN,A-wing
43,Ayla Secura,178.0,55.0,none,blue,hazel,48.0,female,feminine,Ryloth,Twi'lek,"Attack of the Clones, The Phantom Menace, Reve...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,Wicket Systri Warrick,88.0,20.0,brown,brown,brown,8.0,male,masculine,Endor,Ewok,Return of the Jedi,NaN,NaN
11,Wilhuff Tarkin,180.0,NaN,"auburn, grey",fair,blue,64.0,male,masculine,Eriadu,Human,"Revenge of the Sith, A New Hope",NaN,NaN
53,Yarael Poof,264.0,NaN,none,white,yellow,NaN,male,masculine,Quermia,Quermian,The Phantom Menace,NaN,NaN
18,Yoda,66.0,17.0,white,green,brown,896.0,male,masculine,NaN,Yoda's species,"The Empire Strikes Back, Attack of the Clones,...",NaN,NaN
66,Zam Wesell,168.0,55.0,blonde,"fair, green, yellow",yellow,NaN,female,feminine,Zolan,Clawdite,Attack of the Clones,Koro-2 Exodrive airspeeder,NaN

Далее была произведена сортировка по определенным параметрам(выбор впал на имя,которая начинается от A до Z)

In [ ]:
starwars.drop(columns = ["eye_color"])

,name,height,mass,hair_color,skin_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,19.0,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,NaN,gold,112.0,none,masculine,Tatooine,Droid,"The Empire Strikes Back, Attack of the Clones,...",NaN,NaN
2,R2-D2,96.0,32.0,NaN,"white, blue",33.0,none,masculine,Naboo,Droid,"The Empire Strikes Back, Attack of the Clones,...",NaN,NaN
3,Darth Vader,202.0,136.0,none,white,41.9,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...",NaN,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,19.0,female,feminine,Alderaan,Human,"The Empire Strikes Back, Revenge of the Sith, ...",Imperial Speeder Bike,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,NaN,female,feminine,NaN,Human,The Force Awakens,NaN,NaN
83,Poe Dameron,NaN,NaN,brown,light,NaN,male,masculine,NaN,Human,The Force Awakens,NaN,T-70 X-wing fighter
84,BB8,NaN,NaN,none,none,NaN,none,masculine,NaN,Droid,The Force Awakens,NaN,NaN
85,Captain Phasma,NaN,NaN,unknown,unknown,NaN,NaN,NaN,NaN,NaN,The Force Awakens,NaN,NaN
86,Padmé Amidala,165.0,45.0,brown,light,46.0,female,feminine,Naboo,Human,"Attack of the Clones, The Phantom Menace, Reve...",NaN,"H-type Nubian yacht, Naboo star skiff, Naboo f..."

Было произвидено удаление столбца eye_color.

In [ ]:
starwars = starwars.replace(np.nan, "N/A")

Здесь было произведено замена пустых ячеек на N/A.

In [ ]:
starwars.drop_duplicates()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19.0,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,N/A,gold,yellow,112.0,none,masculine,Tatooine,Droid,"The Empire Strikes Back, Attack of the Clones,...",N/A,N/A
2,R2-D2,96.0,32.0,N/A,"white, blue",red,33.0,none,masculine,Naboo,Droid,"The Empire Strikes Back, Attack of the Clones,...",N/A,N/A
3,Darth Vader,202.0,136.0,none,white,yellow,41.9,male,masculine,Tatooine,Human,"The Empire Strikes Back, Revenge of the Sith, ...",N/A,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,brown,19.0,female,feminine,Alderaan,Human,"The Empire Strikes Back, Revenge of the Sith, ...",Imperial Speeder Bike,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Rey,N/A,N/A,brown,light,hazel,N/A,female,feminine,N/A,Human,The Force Awakens,N/A,N/A
83,Poe Dameron,N/A,N/A,brown,light,brown,N/A,male,masculine,N/A,Human,The Force Awakens,N/A,T-70 X-wing fighter
84,BB8,N/A,N/A,none,none,black,N/A,none,masculine,N/A,Droid,The Force Awakens,N/A,N/A
85,Captain Phasma,N/A,N/A,unknown,unknown,unknown,N/A,N/A,N/A,N/A,N/A,The Force Awakens,N/A,N/A
86,Padmé Amidala,165.0,45.0,brown,light,brown,46.0,female,feminine,Naboo,Human,"Attack of the Clones, The Phantom Menace, Reve...",N/A,"H-type Nubian yacht, Naboo star skiff, Naboo f..."

Затем были удалены дубликаты.

In [ ]:
starwars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        87 non-null     object
 1   height      87 non-null     object
 2   mass        87 non-null     object
 3   hair_color  87 non-null     object
 4   skin_color  87 non-null     object
 5   eye_color   87 non-null     object
 6   birth_year  87 non-null     object
 7   sex         87 non-null     object
 8   gender      87 non-null     object
 9   homeworld   87 non-null     object
 10  species     87 non-null     object
 11  films       87 non-null     object
 12  vehicles    87 non-null     object
 13  starships   87 non-null     object
dtypes: object(14)
memory usage: 9.6+ KB

Далее для получения общей информации, используем info.Результат работы функции показывает общую структуру таблицы данных о персонажах из звездных войн. Таблица содержит 87 записей (строк) и 14 столбцов. Каждый столбец представлен своим именем и типом данных.Каждый столбец содержит определенный тип данных, указанный рядом со своим именем. Например, столбец name имеет тип данных object, что означает текстовое значение. Таким образом, можно сказать, что таблица содержит информацию о различных персонажах из фильмов "Звездные войны", включая их атрибуты, связанные с внешностью, принадлежностью к различным видам и владением транспортных средств и космических кораблей.

In [ ]:
starwars.describe

<bound method NDFrame.describe of               name height   mass hair_color   skin_color eye_color birth_year  \
0   Luke Skywalker  172.0   77.0      blond         fair      blue       19.0
1            C-3PO  167.0   75.0        N/A         gold    yellow      112.0
2            R2-D2   96.0   32.0        N/A  white, blue       red       33.0
3      Darth Vader  202.0  136.0       none        white    yellow       41.9
4      Leia Organa  150.0   49.0      brown        light     brown       19.0
..             ...    ...    ...        ...          ...       ...        ...
82             Rey    N/A    N/A      brown        light     hazel        N/A
83     Poe Dameron    N/A    N/A      brown        light     brown        N/A
84             BB8    N/A    N/A       none         none     black        N/A
85  Captain Phasma    N/A    N/A    unknown      unknown   unknown        N/A
86   Padmé Amidala  165.0   45.0      brown        light     brown       46.0

       sex     gender homeworld species  \
0     male  masculine  Tatooine   Human
1     none  masculine  Tatooine   Droid
2     none  masculine     Naboo   Droid
3     male  masculine  Tatooine   Human
4   female   feminine  Alderaan   Human
..     ...        ...       ...     ...
82  female   feminine       N/A   Human
83    male  masculine       N/A   Human
84    none  masculine       N/A   Droid
85     N/A        N/A       N/A     N/A
86  female   feminine     Naboo   Human

                                                films  \
0   The Empire Strikes Back, Revenge of the Sith, ...
1   The Empire Strikes Back, Attack of the Clones,...
2   The Empire Strikes Back, Attack of the Clones,...
3   The Empire Strikes Back, Revenge of the Sith, ...
4   The Empire Strikes Back, Revenge of the Sith, ...
..                                                ...
82                                  The Force Awakens
83                                  The Force Awakens
84                                  The Force Awakens
85                                  The Force Awakens
86  Attack of the Clones, The Phantom Menace, Reve...

                              vehicles  \
0   Snowspeeder, Imperial Speeder Bike
1                                  N/A
2                                  N/A
3                                  N/A
4                Imperial Speeder Bike
..                                 ...
82                                 N/A
83                                 N/A
84                                 N/A
85                                 N/A
86                                 N/A

                                            starships
0                            X-wing, Imperial shuttle
1                                                 N/A
2                                                 N/A
3                                     TIE Advanced x1
4                                                 N/A
..                                                ...
82                                                N/A
83                                T-70 X-wing fighter
84                                                N/A
85                                                N/A
86  H-type Nubian yacht, Naboo star skiff, Naboo f...

[87 rows x 14 columns]>

После чего был проведен анализ.Производится анализ набора данных, представляющего персонажей из вселенной Star Wars. Данные о персонажах содержат различные характеристики, такие как имя, рост, вес, цвет волос, цвет кожи, цвет глаз, год рождения, пол, род и другие.

describe() <-(функция), используется для получения основных статистических характеристик, таких как среднее значение, стандартное отклонение, минимум и максимум для числовых столбцов, таких как рост, вес и год рождения.

In [ ]:
selected_data = starwars.loc[0:5, ["name",	"height",	"mass", "films"]]
print(selected_data)

             name height   mass  \
0  Luke Skywalker  172.0   77.0
1           C-3PO  167.0   75.0
2           R2-D2   96.0   32.0
3     Darth Vader  202.0  136.0
4     Leia Organa  150.0   49.0
5       Owen Lars  178.0  120.0

                                               films
0  The Empire Strikes Back, Revenge of the Sith, ...
1  The Empire Strikes Back, Attack of the Clones,...
2  The Empire Strikes Back, Attack of the Clones,...
3  The Empire Strikes Back, Revenge of the Sith, ...
4  The Empire Strikes Back, Revenge of the Sith, ...
5  Attack of the Clones, Revenge of the Sith, A N...

Далее была проведена выборка данных по строкам и столбцам с помощью loc.

selected_data = starwars.loc[0:5, ["name", "height", "mass", "films"]] использует метод loc для создания подвыборки данных из исходного набора данных starwars.

Метод loc:

loc - это метод для индексации и выборки данных в DataFrame на основе меток (имен строк и столбцов).
Использование loc для выбора строк и столбцов:

starwars.loc[0:5, ["name", "height", "mass", "films"]] означает следующее:
0:5 - это диапазон индексов строк от 0 до 5 (включительно). Таким образом, выбираются строки с индексами 0, 1, 2, 3, 4 и 5.
["name", "height", "mass", "films"] - это список названий столбцов, которые мы хотим выбрать из каждой выбранной строки.
Результат выборки:

Результат выборки сохраняется в переменной selected_data.
Выбранные столбцы включают "name" (имя персонажа), "height" (рост), "mass" (масса) и "films" (фильмы, в которых участвовал персонаж).
Вывод selected_data:

Вывод selected_data представляет собой небольшую подвыборку данных, состоящую из первых шести строк (индексы 0-5) и выбранных столбцов.
Каждая строка содержит информацию о имени персонажа, их росте, массе и фильмах, в которых они участвовали.

In [ ]:
starwars.to_csv("star_wars_character_dataset_clear.csv")

Был создан новый датасет

Вывод: Удалось поработать с датасетамом и также была освоена библиотека pandas, а также выполенены задания.